In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [12]:
a = np.array([22, 33, 55])
b = np.array([[1,5,8], [4,9,14], [43, 1, 6],  [4, 1, 4] ])

In [13]:
a

array([22, 33, 55])

In [14]:
b

array([[ 1,  5,  8],
       [ 4,  9, 14],
       [43,  1,  6],
       [ 4,  1,  4]])

In [15]:
z = np.zeros((4,7))

z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [16]:
o = np.ones((3,5))

o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
r = np.random.rand(4,4) * 10

r

array([[0.410059  , 0.24071693, 7.53541547, 0.81151221],
       [1.95593244, 5.72903147, 3.80822939, 8.37666031],
       [0.79382554, 6.86674393, 4.66817229, 9.18462717],
       [2.73459406, 6.13904787, 5.54803354, 9.38197998]])

In [18]:
i = np.eye(15)

i

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [19]:
print(a.shape)
print(b.shape)

(3,)
(4, 3)


In [22]:
c = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ], 
    [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
    ]
])

print(c.shape)

(2, 3, 3)


In [23]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [24]:
print(a.size)
print(b.size)
print(c.size)

3
12
18


In [25]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64
