In [1]:
import numpy as np

In [11]:
x = np.array([4,6,9])
y = np.array([11,15,12])

In [12]:
array_sum = x + y
array_sum

array([15, 21, 21])

In [13]:
array_mult = x * y
array_mult

array([ 44,  90, 108])

In [14]:
x_square = x**2
x_square

array([16, 36, 81])

In [15]:
x_addtwo = x + 2
x_addtwo

array([ 6,  8, 11])

In [16]:
z1 = np.vstack([x , y, array_sum])
z1

array([[ 4,  6,  9],
       [11, 15, 12],
       [15, 21, 21]])

In [17]:
z2 = np.hstack([x , y])
z2

array([ 4,  6,  9, 11, 15, 12])