In [1]:
import numpy as np

In [2]:
x = np.array(
    [
        [11,26,39],
        [18,44,23],
        [17,87,91]
    ]
)

In [15]:
# slicing & indexing

print(x[0][1])
print(x[0, 1])

print(x[0][-1])
print(x[-2][-2])


print(x[0][1:3])
print(x[0][1:])

print(x[0, 1:])

print(x[:, 0])
print(x[1, :])
print(x[1])


# 44 23 87 91
print(x[1:,1:])

# 11 26 18 44
print(x[:2,:2])

26
26
39
44
[26 39]
[26 39]
[26 39]
[11 18 17]
[18 44 23]
[18 44 23]
[[44 23]
 [87 91]]
[[11 26]
 [18 44]]


In [22]:
x_flatten = x.flatten()
print(x_flatten)

[11 26 39 18 44 23 17 87 91]


In [20]:
x_reshaped = x_flatten.reshape(3,3)
x_reshaped

array([[11, 26, 39],
       [18, 44, 23],
       [17, 87, 91]])

In [24]:
a = np.arange(4,16,2)
a

array([ 4,  6,  8, 10, 12, 14])

In [26]:
a1 = np.arange(4,16,2).reshape(3,2)
a1

array([[ 4,  6],
       [ 8, 10],
       [12, 14]])

In [28]:
b = np.arange(100,1,-10)
b

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [29]:
b > 50

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [30]:
b[b>50]

array([100,  90,  80,  70,  60])