In [1]:
!pip install numpy


In [2]:
import numpy as np

## 1 - Students Marks Analysis

In [21]:
marks=np.array([
      78, 85, 67, 90, 56, 88, 72, 95, 60, 81,
    74, 69, 92, 58, 77, 84, 66, 73, 89, 91,
    62, 80, 55, 87, 70, 79, 68, 93, 64, 82,
    76, 59, 86, 71, 83, 65, 94, 57, 75, 88
])
marks

array([78, 85, 67, 90, 56, 88, 72, 95, 60, 81, 74, 69, 92, 58, 77, 84, 66,
       73, 89, 91, 62, 80, 55, 87, 70, 79, 68, 93, 64, 82, 76, 59, 86, 71,
       83, 65, 94, 57, 75, 88])

## . avg

In [4]:
marksAvg=np.average(marks)
marksAvg

np.float64(75.975)

## . Highest

In [5]:
highestMarks=np.max(marks)
highestMarks

np.int64(95)

## . Lowest

In [6]:
lowestMarks=np.min(marks)
lowestMarks

np.int64(55)

## Student Who Scored Above Average

In [11]:
for m in marks:
    if(m>marksAvg): 
        print(m)
    else:
        print(f"Low Marks {m}")

78
85
Low Marks 67
90
Low Marks 56
88
Low Marks 72
95
Low Marks 60
81
Low Marks 74
Low Marks 69
92
Low Marks 58
77
84
Low Marks 66
Low Marks 73
89
91
Low Marks 62
80
Low Marks 55
87
Low Marks 70
79
Low Marks 68
93
Low Marks 64
82
76
Low Marks 59
86
Low Marks 71
83
Low Marks 65
94
Low Marks 57
Low Marks 75
88


In [14]:
marks=marks-5

In [15]:
marks

array([78, 85, 67, 90, 56, 88, 72, 95, 60, 81, 74, 69, 92, 58, 77, 84, 66,
       73, 89, 91, 62, 80, 55, 87, 70, 79, 68, 93, 64, 82, 76, 59, 86, 71,
       83, 65, 94, 57, 75, 88])

## Increase All Marks By 5

In [25]:
marksIncrease=np.clip(marks+5,0,100)


In [26]:
marksIncrease

array([ 83,  90,  72,  95,  61,  93,  77, 100,  65,  86,  79,  74,  97,
        63,  82,  89,  71,  78,  94,  96,  67,  85,  60,  92,  75,  84,
        73,  98,  69,  87,  81,  64,  91,  76,  88,  70,  99,  62,  80,
        93])

# Daily Temperature Monitoring

In [28]:
temperature=np.array([
     30, 32, 31, 29, 28, 33, 35, 34, 36, 37,
    38, 39, 40, 41, 42, 43, 44, 45, 40, 39,
    38, 37, 36, 35, 34, 33, 32, 31, 30, 29
])
temperature

array([30, 32, 31, 29, 28, 33, 35, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29])

## Hottest Day

In [33]:
HottestDay=np.max(temperature)
print(f"Day {np.argmax(temperature)+1} Is The Hotest Day Temperature Was {HottestDay}")

Day 18 Is The Hotest Day Temperature Was 45


In [30]:
HottestDay

np.int64(45)

## Coldest Day

In [35]:
ColdestDay=np.min(temperature)
print(f"Day {np.argmin(temperature)+1} Is The Coldest Day Temperature Was {ColdestDay}")

Day 5 Is The Coldest Day Temperature Was 28


In [32]:
ColdestDay

np.int64(28)

## Weekly Average

In [39]:
Weeks=temperature[:28].reshape(4,7)
Weeks

array([[30, 32, 31, 29, 28, 33, 35],
       [34, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 40, 39, 38],
       [37, 36, 35, 34, 33, 32, 31]])

In [47]:
weeklyAverage=np.mean(Weeks ,axis=1)
weeklyAverage

array([31.14285714, 37.85714286, 41.57142857, 34.        ])

## Days Where Temp Exceed 40 ^c

In [49]:
HieghestDays=np.where(temperature>40)
HieghestDays
        

(array([13, 14, 15, 16, 17]),)

In [51]:
print(f"The Highest Temperature Days Are {HieghestDays[0]+1}")

The Highest Temperature Days Are [14 15 16 17 18]


## Temp To Farenhiet

In [52]:
Farenhiet=(temperature*9/5)+32
Farenhiet

array([ 86. ,  89.6,  87.8,  84.2,  82.4,  91.4,  95. ,  93.2,  96.8,
        98.6, 100.4, 102.2, 104. , 105.8, 107.6, 109.4, 111.2, 113. ,
       104. , 102.2, 100.4,  98.6,  96.8,  95. ,  93.2,  91.4,  89.6,
        87.8,  86. ,  84.2])

# Monthly sale Report 

In [53]:
sales=np.array([
       1200, 1500, 0, 1800, 2000, 0, 1700,
    1600, 1400, 0, 1900, 2100, 2200, 0,
    2300, 2000, 0, 1800, 1700, 1600, 0,
    1500, 1400, 1300, 0, 1200, 1100, 0,
    1000, 900
])

In [54]:
sales

array([1200, 1500,    0, 1800, 2000,    0, 1700, 1600, 1400,    0, 1900,
       2100, 2200,    0, 2300, 2000,    0, 1800, 1700, 1600,    0, 1500,
       1400, 1300,    0, 1200, 1100,    0, 1000,  900])

## Total Monthly Sale

In [56]:
totalSales=np.sum(sales)
totalSales

np.int64(35200)

## Average Daily Sales

In [57]:
SalesAverage=np.mean(sales)
SalesAverage

np.float64(1173.3333333333333)

## Best Sale

In [60]:
BestSale=np.max(sales)
print(f"The Best Sale Day Was {np.argmax(sales)+1}={BestSale}")
BestSale

The Best Sale Day Was 15=2300


np.int64(2300)

## Wrost Sale

In [62]:
wrostSale=np.min(sales)
print(f"The Wrost Sale Day Was {np.argmin(sales)+1}={wrostSale}")
wrostSale

The Wrost Sale Day Was 3=0


np.int64(0)

In [63]:
sales=np.where(sales==0,SalesAverage,sales)
sales

array([1200.        , 1500.        , 1173.33333333, 1800.        ,
       2000.        , 1173.33333333, 1700.        , 1600.        ,
       1400.        , 1173.33333333, 1900.        , 2100.        ,
       2200.        , 1173.33333333, 2300.        , 2000.        ,
       1173.33333333, 1800.        , 1700.        , 1600.        ,
       1173.33333333, 1500.        , 1400.        , 1300.        ,
       1173.33333333, 1200.        , 1100.        , 1173.33333333,
       1000.        ,  900.        ])

# Employee Attandence System

In [81]:
attendance = np.array([
    # Employee 1
    [1,-1,0,1,1,1,0,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1],

    # Employee 2
    [1,0,1,-1,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,0,1],

    # Employee 3
    [0,1,1,0,1,1,1,1,-1,1,0,1,1,1,1,1,1,0,1,1,1,1]
])
attendance

array([[ 1, -1,  0,  1,  1,  1,  0,  1,  1,  1,  1,  0,  1,  1,  1,  0,
         1,  1,  1,  0,  1,  1],
       [ 1,  0,  1, -1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  0,  1,
         1,  1,  1,  1,  0,  1],
       [ 0,  1,  1,  0,  1,  1,  1,  1, -1,  1,  0,  1,  1,  1,  1,  1,
         1,  0,  1,  1,  1,  1]])

## Total Present Days

In [82]:
TotalPresentDays=np.sum(attendance,axis=1)
TotalPresentDays

array([15, 16, 16])

In [83]:
totaldays=attendance.shape[1]
totaldays

22

In [84]:
attendancePercentage=TotalPresentDays/totaldays*100
attendancePercentage

array([68.18181818, 72.72727273, 72.72727273])

In [85]:
LowPercentage=np.where(attendancePercentage<90)[0]
print(f"Hey Employee No : {LowPercentage+1} Your Attendance Is Low")

Hey Employee No : [1 2 3] Your Attendance Is Low


## Replace -1 with zero

In [86]:
attendance=np.where(attendance==-1,0,attendance)
attendance

array([[1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1]])

# Website Traffic Analysis

In [3]:
traffic=np.array([
        120, 80, 60, 50, 40, 70,
    150, 300, 500, 650, 700, 800,
    900, 850, 780, 600, 550, 500,
    450, 400, 350, 300, 200, 150
])

In [4]:
traffic

array([120,  80,  60,  50,  40,  70, 150, 300, 500, 650, 700, 800, 900,
       850, 780, 600, 550, 500, 450, 400, 350, 300, 200, 150])

## Peak Hours

In [5]:
peakHours=np.argmax(traffic)
print(f"Peak Hours : {peakHours+1}")
print(f"Visitors : {traffic[peakHours]}")

Peak Hours : 13
Visitors : 900


## Total Daily Visitors

In [7]:
TotalVisitors=np.sum(traffic)
print(f"Total Visitors : {TotalVisitors}")

Total Visitors : 9550


## Hours Below Average


In [8]:
trafficAvg=np.mean(traffic)

In [10]:
belowHours=np.where(traffic < trafficAvg)[0]+1
print(f"Hours Below Average : {belowHours}")

Hours Below Average : [ 1  2  3  4  5  6  7  8 21 22 23 24]
